source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'AdManagerRewardedVideoExample' do
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationInMobi'
  pod 'GoogleMobileAdsMediationAppLovin'
  pod 'GoogleMobileAdsMediationUnity'
end
